version: '3.9'
services:
  postgres:
    container_name: postgres
    image: "postgres:14.5-alpine"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=gamelib-db
      - POSTGRES_USER=gamelib
      - POSTGRES_PASSWORD=P@ssw0rd
    healthcheck:
      test: pg_isready -U gamelib -d gamelib-db
      interval: 5s
      timeout: 5s
      retries: 5

  migrate:
    container_name: migrate
    image: migrate/migrate
    volumes:
      - ./postgre/migrations:/migrations
    command: [ "-path", "/migrations", "-database", "postgres://gamelib:P@ssw0rd@postgres:5432/gamelib-db?sslmode=disable", "up"]
    restart: "on-failure"
    depends_on:
      - postgres
    links:
      - postgres

  minio:
    container_name: minio
    image: minio/minio:latest
    command: server /data --console-address ":9001"
    restart: always
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      -  ~/minio/data:/data
    environment:
      - MINIO_ROOT_USER=gamelib
      - MINIO_ROOT_PASSWORD=P@ssw0rd
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  gamelib:
    container_name: gamelib
    build: ./
    command: ["./app", "-env=test"]
    environment: []
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio