server:
  port: 8080

storage:
  host: 127.0.0.1
  port: 5432
  name: gamelib
  password: P@ssw0rd
  dbname: gamelib-db
  sslMode: disable

minio:
  host: 127.0.0.1
  port: 9000
  access_key: "eIh66BvknLnu2lJm7Kdx"
  secret_key: "ChIwcMebfX6NP3Y9fazOKqXF6pjcysTPEXmuhPqY"
  image_bucket_name: "image"
  ssl: false
